package Entities;

public enum Permission {
    CREATE_A_DIRECTOR,

    CREATE_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,

    CREATE_TEACHER,
    UPDATE_TEACHER,
    DELETE_TEACHER,

    CREATE_COURSE,
    UPDATE_COURSE,
    DELETE_COURSE,

    REGISTER_STUDENT_TO_COURSE,
    REGISTER_TEACHER_TO_COURSE
}
